# Generated by Django 4.2 on 2023-06-05 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_traderuser_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(upload_to='profile_pics')),
                ('phone_number', models.IntegerField(max_length=10, validators=[django.core.validators.MinValueValidator(10, message='Phone numbers have 10 digits!')])),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
