# Generated by Django 4.2 on 2023-06-05 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_traderprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderuser',
            name='slug',
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traderprofile',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone numbers must start with 0 and have 10 digits.', regex='^0[0-9]{9}$')]),
        ),
    ]
