# Generated by Django 4.2 on 2023-06-05 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_traderuser_slug_traderprofile_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone numbers must start with 0 and have 10 digits.', regex='^0[0-9]{9}$')]),
        ),
    ]
