# Generated by Django 4.2 on 2023-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_traderprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='first_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='last_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
