# Generated by Django 4.2 on 2023-06-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_traderprofile_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='place_of_living',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
