# Generated by Django 4.2 on 2023-06-05 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('VAN', 'Van'), ('SUV', 'SUV'), ('CAB', 'Cabrio'), ('UNI', 'Station Wagon'), ('COU', 'Coupe'), ('MIN', 'Minivan'), ('PIC', 'Pickup'), ('SED', 'Sedan'), ('LIM', 'Limousine'), ('HAT', 'Hatchback')], max_length=3)),
                ('gearbox_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('S', 'Semi-automatic')], max_length=1)),
                ('engine_type', models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel'), ('E', 'Electric'), ('H', 'Hybrid'), ('I', 'Plug-in Hybrid')], max_length=1)),
                ('engine_power', models.IntegerField()),
                ('engine_volume', models.IntegerField()),
                ('eurostandard', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('production_date', models.DateField()),
                ('color', models.CharField(choices=[('W', 'White'), ('B', 'Black'), ('G', 'Gray'), ('S', 'Silver'), ('U', 'Blue'), ('R', 'Red'), ('N', 'Brown'), ('G', 'Green'), ('O', 'Orange'), ('L', 'Gold'), ('Y', 'Yellow'), ('P', 'Purple')], max_length=1)),
                ('condition', models.CharField(blank=True, choices=[('N', 'New'), ('U', 'Used'), ('F', 'For parts')], default='U', max_length=1, null=True)),
                ('price', models.IntegerField()),
                ('region', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=64)),
                ('seller', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='car_images')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trader.car')),
            ],
        ),
    ]
