# Generated by Django 4.2 on 2023-04-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel'), ('E', 'Electric'), ('H', 'Hybrid'), ('I', 'Plug-in Hybrid')], max_length=1)),
                ('power', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='place',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='production_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='model',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='eurostandard',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trader.engine'),
            preserve_default=False,
        ),
    ]
