# Generated by Django 4.2 on 2023-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_car_model_alter_car_category_alter_car_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel'), ('E', 'Electric'), ('H', 'Hybrid'), ('I', 'Plug-in Hybrid')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
