# Generated by Django 4.2 on 2023-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_carmanufacturer_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmanufacturer',
            name='manufacturer',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
