# Generated by Django 4.2 on 2023-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_remove_car_engine_car_engine_power_car_engine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('VAN', 'Van'), ('SUV', 'SUV'), ('CAB', 'Cabrio'), ('UNI', 'Universal'), ('COU', 'Coupe'), ('MIN', 'Minivan'), ('PIC', 'Pickup'), ('SED', 'Sedan'), ('LIM', 'Limousine'), ('HAT', 'Hatchback')], max_length=3),
        ),
    ]
