# Generated by Django 4.2 on 2023-06-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_alter_carmanufacturer_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
    ]
