# Generated by Django 4.2 on 2023-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_alter_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('F', 'For parts')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox_type',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('S', 'Semi-automatic')], max_length=1),
        ),
    ]
