# Generated by Django 4.2 on 2023-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_car_condition_alter_car_gearbox_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('F', 'For parts')], default='U', max_length=1),
        ),
    ]
