# Generated by Django 4.2 on 2023-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_alter_car_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(default=None, upload_to='static/trader/car_pictures'),
            preserve_default=False,
        ),
    ]
