# Generated by Django 4.2 on 2023-04-29 21:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_car_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/car_pictures'), upload_to=''),
        ),
    ]
