# Generated by Django 4.2 on 2023-04-30 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_alter_car_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='picture',
        ),
        migrations.CreateModel(
            name='CarPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trader.car')),
            ],
        ),
    ]
