# Generated by Django 4.2 on 2023-05-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0015_remove_carpictures_car_id_car_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pictures',
        ),
        migrations.AddField(
            model_name='carpictures',
            name='car_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='trader.car'),
            preserve_default=False,
        ),
    ]
